### ISSUE TITLE
Sync didn't work properly

### ISSUE THREAD

**Issue by juliusremes** [tomer-ha/LoopToIosConverter#2]
After migration and import my loop database into the unofficial iOS app, the app shows me the habits correctly, but obviously without records.
Is there something to consider or has something the app changed which could have cased this behavior?

**Comment by tomer-ha** [comment]
Hey @juliusremes, would you mind sharing your db file from Loop? It would help me debugging the issue. You can change your habit names etc. and re-export if you don't want me to see your personal information.
If not, I can try to instruct you, but it will take much longer.

**Comment by juliusremes** [comment]
Hey @tomer-ha, yeah, I could do that. I will upload it here and will delete it when you've downloaded it, okay?
So, a short note, that you've downloaded the file, would be nice!
[2022-10-25 LoopToIosConverter.zip](https://github.com/tomer-ha/LoopToIosConverter/files/9944434/2022-10-25.LoopToIosConverter.zip)

**Comment by tomer-ha** [comment]
I downloaded it, thanks. From a quick look, it looks like the csv file contains completion dates.
I'll try to import it to iOS and see what's wrong. I don't know if it'll be today though.

**Comment by tomer-ha** [comment]
OK, ran a quick test. I tried to import the csv file you generated and indeed no dates were imported.
Then I tried to run the converter tool again, generated a csv file and imported, and this time I could see dates.

I attach here the csv file I generated. I still don't know what's the difference, but while I investigate further you can import your habits and go on with your life :)

[working.csv](https://github.com/tomer-ha/LoopToIosConverter/files/9944547/working.csv)

**Comment by tomer-ha** [comment]
I think I figured it out, the difference between my file and yours is the decimal point. You're using a locale that's formatting the decimal point as a comma, so "1.0" becomes "1,0.". This messes with the csv file format, causing everything to shift a place.
I'll try to issue a fix soon, but I think that's enough for today. :)

**Comment by juliusremes** [comment]
Wow, I didn't even expect such fast support, neither did I think about such a fast fix! It's working now. 
Thank you! Much appreciation!
